### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by darcyrao** [statnet/WHAMP#82]
Mortality with HIV
- [ ] Calculate the age-specific mortality rates for 2016 and 2017 from the data Steve Erly sent and average them. May want to collapse some of the age groups due to small numbers. 
- [ ] Calculate the age-specific mortality rates in the general population for the corresponding age groups. Do this by weighting the race-specific general population mortality rates by the proportion of PLWHA in 2017 in each race group to get the expected background mortality for the population of PLWHA. 
- [ ] Calculate the multiplier we would want to multiply background mortality by for HIV+ men in each age group. Revise the model code.

HIV care cascade
- [ ] Once I get new data from Steve Erly, recalculate the time from diagnosis to ART initiation assuming ART initiation is ~6-8 weeks before viral suppression (should see time from dx to ART around 6-8 weeks). Recalculate the probability of treatment cessation.
- [ ] Revise the code to calculate the rate of reinitiating treatment using the stationary distribution of a Markov Chain formula (issue #81). Also incorporate assumption of different rate of discontinuing for partial suppressors if Matt thinks we should do this.
- [ ] Implement procedure to calculate the proportion of men in the non-regular tester group to match the proportion of new diagnoses that are late diagnoses (see issue #81).
- [ ] Modify the code to assume that men in this non-regular tester group develop symptoms and are diagnosed in a median of 8 years. Could implement this as a fixed interval or do it as in the routine testing model where I assume a probability of 8.8% of developing AIDS-associated symptoms in the first year and a 6% probability in each subsequent year after seroconversion, but that would take people up through a max of 16 years whereas we are assuming 10 years to AIDS. Probably simpler to just assume a fixed interval.
- [ ] Modify the code to not assume that partial suppressors progress to AIDS in 15 years. But for all groups, AIDS if cumulative time off treatment >10 years (see issue #81).
- [ ] Once I get new data from Steve Erly, run imputation ABC procedure to find the raceXregion values that satisfy the margins within a margin of acceptance.

Other
- Add to decisions file documenting why we are not modeling STIs (see issue #81).
- Try the persistent model fit using the control.stergm settings in the refitting simulation algorithm to match the diagnostics. Do it with 2% noise, 7% noise, and variable noise, all with 10K sims.
